# Generated by Django 2.2.12 on 2024-12-09 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='user_type',
            field=models.CharField(choices=[('expert', 'Expert'), ('inquirer', 'Inquirer')], default='inquirer', max_length=20),
        ),
        migrations.CreateModel(
            name='expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.CharField(max_length=100)),
                ('max_tasks', models.IntegerField(default=3)),
                ('skill_level', models.IntegerField(default=1)),
                ('arrive_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_time', models.DateTimeField(default=datetime.timedelta(days=1))),
                ('credibility', models.CharField(default=0.5, max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.NormalUser')),
            ],
        ),
        migrations.CreateModel(
            name='asker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.NormalUser')),
            ],
        ),
    ]
